export const toursData = [
  {
    title: "Sundarbans Mangrove Safari",
    slug: "sundarbans-mangrove-safari",
    description:
      "Explore the world's largest mangrove forest and spot the majestic Royal Bengal Tiger.",
    images: [require("../../assets/tour/1.jpg")],
    location: "Sundarbans, Khulna",
    costFrom: 15000,
    startDate: "2026-10-15T08:00:00.000Z",
    endDate: "2026-10-18T17:00:00.000Z",
    departureLocation: "Khulna River Port",
    arrivalLocation: "Khulna River Port",
    included: [
      "Accommodation on cruise",
      "All meals",
      "Forest permission fees",
      "Armed guard",
    ],
    excluded: ["Personal expenses", "Camera fees", "Travel to Khulna"],
    amenities: ["Air-conditioned cabins", "Dining area", "First aid"],
    tourPlan: [
      "Day 1: Boarding and Harbaria",
      "Day 2: Kotka and Jamtola Beach",
      "Day 3: Karamjal and Return",
    ],
    maxGuest: 30,
    minAge: 10,
    division: "Khulna Division",
    tourType: "Wildlife Safari",
  },
  {
    title: "Cox's Bazar Beach Getaway",
    slug: "coxs-bazar-beach-getaway",
    description: "Relax on the longest unbroken sea beach in the world.",
    images: [require("../../assets/tour/2.jpg")],
    location: "Cox's Bazar, Chittagong",
    costFrom: 12000,
    startDate: "2026-11-01T10:00:00.000Z",
    endDate: "2026-11-04T12:00:00.000Z",
    departureLocation: "Dhaka",
    arrivalLocation: "Cox's Bazar",
    included: ["Hotel accommodation", "Breakfast", "Bus tickets"],
    excluded: ["Lunch and Dinner", "Water sports", "Personal expenses"],
    amenities: ["Swimming pool", "Free Wi-Fi", "Ocean view rooms"],
    tourPlan: [
      "Day 1: Arrival and Beach walk",
      "Day 2: Inani Beach and Himchari",
      "Day 3: Marine Drive",
      "Day 4: Departure",
    ],
    maxGuest: 40,
    minAge: 0,
    division: "Chittagong Division",
    tourType: "Beach Holiday",
  },
  {
    title: "Sylhet Tea Garden & Waterfall Tour",
    slug: "sylhet-tea-garden-waterfall-tour",
    description:
      "Experience the lush green tea estates and the beautiful Bisnakandi waterfall.",
    images: [require("../../assets/tour/3.jpg")],
    location: "Sylhet",
    costFrom: 9500,
    startDate: "2026-09-10T07:00:00.000Z",
    endDate: "2026-09-12T20:00:00.000Z",
    departureLocation: "Sylhet City Center",
    arrivalLocation: "Sylhet City Center",
    included: ["Transport within Sylhet", "Guide", "Hotel stay"],
    excluded: ["Food", "Boat rides"],
    amenities: ["Comfortable transport", "Experienced guide"],
    tourPlan: [
      "Day 1: Ratargul Swamp Forest",
      "Day 2: Bisnakandi",
      "Day 3: Jaflong and Return",
    ],
    maxGuest: 15,
    minAge: 5,
    division: "Sylhet Division",
    tourType: "Nature & Sightseeing",
  },
  {
    title: "Bandarban Cloud Trekking",
    slug: "bandarban-cloud-trekking",
    description:
      "Trek through the hills of Bandarban and touch the clouds at Nilgiri.",
    images: [require("../../assets/tour/4.jpg")],
    location: "Bandarban",
    costFrom: 8000,
    startDate: "2026-12-05T06:00:00.000Z",
    endDate: "2026-12-07T18:00:00.000Z",
    departureLocation: "Chittagong",
    arrivalLocation: "Chittagong",
    included: ["Chander Gari transport", "Cottage stay", "Tribal food tasting"],
    excluded: ["Trekking gear", "Standard meals"],
    amenities: ["Local guide", "Campfire"],
    tourPlan: [
      "Day 1: Boga Lake",
      "Day 2: Keokradong Trek",
      "Day 3: Nilgiri and Return",
    ],
    maxGuest: 12,
    minAge: 16,
    division: "Chittagong Division",
    tourType: "Trekking & Adventure",
  },
  {
    title: "Old Dhaka Heritage Walk",
    slug: "old-dhaka-heritage-walk",
    description:
      "Discover the rich history, architecture, and culinary delights of Old Dhaka.",
    images: [require("../../assets/tour/5.jpg")],
    location: "Old Dhaka",
    costFrom: 2000,
    startDate: "2026-08-25T14:00:00.000Z",
    endDate: "2026-08-25T20:00:00.000Z",
    departureLocation: "Curzon Hall, DU",
    arrivalLocation: "Ahsan Manzil",
    included: ["Walking guide", "Street food tasting", "Entry tickets"],
    excluded: ["Transport to meeting point"],
    amenities: ["Bottled water", "Audio headsets"],
    tourPlan: [
      "14:00: Curzon Hall",
      "15:30: Lalbagh Fort",
      "17:00: Star Mosque",
      "18:30: Ahsan Manzil and Dinner",
    ],
    maxGuest: 20,
    minAge: 12,
    division: "Dhaka Division",
    tourType: "Heritage & Cultural",
  },
];
